import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Providers from "@/lib/Providers/Providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Lost and Found",
  description: "Generated by Lost and Found",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" suppressHydrationWarning >
        <body>
          <AppRouterCacheProvider>
            <div>
            <Toaster position="top-center" />
            {children}
            </div>
          </AppRouterCacheProvider>
        </body>
      </html>
    </Providers>
  );
}
